name: development-server
services:
  postgres-db:
    container_name: postgressql
    image: postgres:18-bookworm
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin1234
    restart: unless-stopped
    command:
      - bash
      - -c
      - |
        apt-get update
        apt-get install -y postgresql-18-pgvector
        exec docker-entrypoint.sh postgres
    volumes:
      - postgresql_data:/var/lib/postgresql

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      - PGADMIN_DEFAULT_PASSWORD=test
      - PGADMIN_DEFAULT_EMAIL=test@prathamesh.com
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  minio:
    container_name: minio-blobstorage
    image: quay.io/minio/aistor/minio:latest
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio/data:/mnt/data
      - ./minio/minio.license:/minio.license
      - ./minio/certs:/etc/minio/certs
    command: >
      minio server /mnt/data --license /minio.license

  papercut:
    image: changemakerstudiosus/papercut-smtp:latest
    container_name: papercut-smtp
    ports:
      - "37408:8080"
      - "2525:2525"
    environment:
      - SmtpServer__IP=0.0.0.0
      - SmtpServer__Port=2525
      - Urls=http://0.0.0.0:8080
    restart: unless-stopped

volumes:
  pgadmin_data:
  postgresql_data:
  papercut-messages:
