name: Portfolio

services:
  strapi-cms:
    container_name: strapi-cms
    image: ${REGISTRY}/portfolio/strapi-cms:latest
    restart: unless-stopped
    pull_policy: always
    cpus: 0.6
    mem_limit: 448m
    mem_reservation: 384m
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"
    environment:
      - APP_KEYS=${APP_KEYS}
      - API_TOKEN_SALT=${API_TOKEN_SALT}
      - ADMIN_JWT_SECRET=${ADMIN_JWT_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - TRANSFER_TOKEN_SALT=${TRANSFER_TOKEN_SALT}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - STRAPI_TELEMETRY_DISABLED=true
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=portfolio-cms
      - DATABASE_USERNAME=prathamesh
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_CLIENT=postgres
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - AWS_ENDPOINT=${AWS_ENDPOINT}
      - ASSISTANT_URL=https://ai-assistant.prathameshdhande.com
      - ASSISTANT_SECRET=${ASSISTANT_SECRET}
      - CLIENT_URL=https://prathameshdhande.com
      - REVALIDATE_SECRET=${REVALIDATE_SECRET}
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.strapi.rule=Host(`cms.prathameshdhande.com`)
      - traefik.http.routers.strapi.entrypoints=https
      - traefik.http.routers.strapi.tls=true
      - traefik.http.routers.strapi.tls.certresolver=spaceship
      - traefik.http.middlewares.strapi-limit.buffering.maxRequestBodyBytes=104857600
      - traefik.http.routers.strapi.middlewares=strap-limit
      - traefik.http.services.strapi-cms-service.loadbalancer.server.port=1337
      - traefik.http.routers.strapi.service=strapi-cms-service
    networks:
      - proxy
      - pg-database

networks:
  proxy: 
    external: true
  pg-database:
    external: true