import type { IconType } from "react-icons";
import {
  SiAngular,
  SiApachemaven,
  SiBootstrap,
  SiC,
  SiCplusplus,
  SiCss,
  SiDjango,
  SiDocker,
  SiDotnet,
  SiExpress,
  SiFastapi,
  SiFlask,
  SiGit,
  SiGithub,
  SiGithubactions,
  SiGraphql,
  SiHtml5,
  SiJavascript,
  SiJest,
  SiJquery,
  SiJupyter,
  SiKeras,
  SiKubernetes,
  SiLangchain,
  SiLeetcode,
  SiLinux,
  SiMongodb,
  SiMui,
  SiMysql,
  SiNestjs,
  SiNextdotjs,
  SiNgrx,
  SiNodedotjs,
  SiNumpy,
  SiPandas,
  SiPostgresql,
  SiPostman,
  SiPrisma,
  SiPython,
  SiPytorch,
  SiR,
  SiReact,
  SiReactivex,
  SiRedis,
  SiRedux,
  SiScikitlearn,
  SiSpring,
  SiSqlite,
  SiStrapi,
  SiStreamlit,
  SiTailwindcss,
  SiTensorflow,
  SiTypescript,
  SiVite,
  SiVuedotjs,
  SiHackerrank,
  SiGnubash,
  SiRecoil,
  SiAxios,
  SiLangchaincorporate,
  SiNginx,
  SiLanggraph,
  SiPodman,
  SiUbuntu,
  SiTraefikproxy,
  SiIntellijidea,
  SiEclipseide,
  SiRstudioide,
  SiNuget,
  SiPoetry,
  SiYarn,
  SiNpm,
  SiUv,
  SiZod,
  SiAntdesign,
  SiGooglegemini,
  SiIonic,
  SiPydantic,
  SiSqlalchemy
} from "react-icons/si";
import {
  FaBehance,
  FaCodepen,
  FaDev,
  FaDribbble,
  FaEnvelope,
  FaFacebook,
  FaGlobe,
  FaInstagram,
  FaJava,
  FaMedium,
  FaStackOverflow,
  FaXTwitter,
  FaYoutube,
} from "react-icons/fa6";
import { BsWindows } from "react-icons/bs";
import { FaAws, FaLinkedinIn } from "react-icons/fa";
import { VscMcp, VscVscode } from "react-icons/vsc";
import {
  LuArrowLeft,
  LuArrowRight,
  LuArrowUp,
  LuArrowUpRight,
  LuCheck,
  LuChevronRight,
  LuCopy,
  LuDownload,
  LuExternalLink,
  LuFileText,
  LuLoaderCircle,
  LuMail,
  LuMenu,
  LuMoon,
  LuSparkles,
  LuSun,
  LuX,
} from "react-icons/lu";
import { TbBrandAdobePhotoshop, TbBrandAdobePremiere, TbBrandCSharp } from "react-icons/tb";
import { DiDotnet, DiVim, DiVisualstudio } from "react-icons/di";

export const ICON_REGISTRY: Record<string, IconType> = {
  SiGnubash,
  SiAngular,
  SiApachemaven,
  SiBootstrap,
  SiC,
  SiCplusplus,
  SiCss,
  SiDjango,
  SiDocker,
  SiDotnet,
  SiExpress,
  SiFastapi,
  SiFlask,
  SiGit,
  SiGithub,
  SiGithubactions,
  SiGraphql,
  SiHackerrank,
  SiHtml5,
  SiJavascript,
  SiJest,
  SiJquery,
  SiJupyter,
  SiKeras,
  SiKubernetes,
  SiLangchain,
  SiLeetcode,
  SiLinux,
  SiMongodb,
  SiMui,
  SiMysql,
  SiNestjs,
  SiNextdotjs,
  SiNgrx,
  SiNodedotjs,
  SiNumpy,
  SiPandas,
  SiPostgresql,
  SiPostman,
  SiPrisma,
  SiPython,
  SiPytorch,
  SiR,
  SiReact,
  SiReactivex,
  SiRedis,
  SiRedux,
  SiScikitlearn,
  TbBrandCSharp,
  SiRecoil,
  SiSpring,
  SiSqlite,
  SiStrapi,
  SiStreamlit,
  SiTailwindcss,
  SiTensorflow,
  SiTypescript,
  SiVite,
  SiVuedotjs,
  SiAxios,
  FaAws,
  SiLangchaincorporate,
  SiNginx,
  SiLanggraph,
  SiPodman,
  SiUbuntu,
  SiTraefikproxy,
  BsWindows,
  SiIntellijidea,
  SiEclipseide,
  TbBrandAdobePhotoshop,
  TbBrandAdobePremiere,
  SiRstudioide,
  SiNuget,
  SiPoetry,
  SiYarn,
  SiNpm,
  SiUv,
  DiVim,
  DiVisualstudio,
  SiZod,
  SiAntdesign,
  VscMcp,
  SiGooglegemini,
  SiIonic,
  SiPydantic,
  DiDotnet,
  SiSqlalchemy,
  VscVscode,

  FaBehance,
  FaCodepen,
  FaDev,
  FaDribbble,
  FaEnvelope,
  FaFacebook,
  FaGlobe,
  FaInstagram,
  FaJava,
  FaLinkedinIn,
  FaMedium,
  FaStackOverflow,
  FaXTwitter,
  FaYoutube,

  LuArrowLeft,
  LuArrowRight,
  LuArrowUp,
  LuArrowUpRight,
  LuCheck,
  LuChevronRight,
  LuCopy,
  LuDownload,
  LuExternalLink,
  LuFileText,
  LuLoaderCircle,
  LuMail,
  LuMenu,
  LuMoon,
  LuSparkles,
  LuSun,
  LuX,
};

export const PLATFORM_ICON: Record<string, IconType> = {
  github: SiGithub,
  linkedin: FaLinkedinIn,
  twitter: FaXTwitter,
  instagram: FaInstagram,
  facebook: FaFacebook,
  youtube: FaYoutube,
  medium: FaMedium,
  devto: FaDev,
  stackoverflow: FaStackOverflow,
  leetcode: SiLeetcode,
  hackerrank: SiHackerrank,
  codepen: FaCodepen,
  behance: FaBehance,
  dribbble: FaDribbble,
  email: FaEnvelope,
  website: FaGlobe,
};
