import type { IconType } from "react-icons";
import {
  SiAngular,
  SiApachemaven,
  SiBootstrap,
  SiC,
  SiCplusplus,
  SiCss,
  SiDjango,
  SiDocker,
  SiDotnet,
  SiExpress,
  SiFastapi,
  SiFlask,
  SiGit,
  SiGithub,
  SiGithubactions,
  SiGraphql,
  SiHtml5,
  SiJavascript,
  SiJest,
  SiJquery,
  SiJupyter,
  SiKeras,
  SiKubernetes,
  SiLangchain,
  SiLeetcode,
  SiLinux,
  SiMongodb,
  SiMui,
  SiMysql,
  SiNestjs,
  SiNextdotjs,
  SiNgrx,
  SiNodedotjs,
  SiNumpy,
  SiPandas,
  SiPostgresql,
  SiPostman,
  SiPrisma,
  SiPython,
  SiPytorch,
  SiR,
  SiReact,
  SiReactivex,
  SiRedis,
  SiRedux,
  SiScikitlearn,
  SiSharp,
  SiSpring,
  SiSqlite,
  SiStrapi,
  SiStreamlit,
  SiTailwindcss,
  SiTensorflow,
  SiTypescript,
  SiVite,
  SiVuedotjs,
  SiHackerrank,
} from "react-icons/si";
import {
  FaBehance,
  FaCodepen,
  FaDev,
  FaDribbble,
  FaEnvelope,
  FaFacebook,
  FaGlobe,
  FaInstagram,
  FaJava,
  FaMedium,
  FaStackOverflow,
  FaXTwitter,
  FaYoutube,
} from "react-icons/fa6";
import { FaLinkedinIn } from "react-icons/fa";
import {
  LuArrowLeft,
  LuArrowRight,
  LuArrowUp,
  LuArrowUpRight,
  LuCheck,
  LuChevronRight,
  LuCopy,
  LuDownload,
  LuExternalLink,
  LuFileText,
  LuLoaderCircle,
  LuMail,
  LuMenu,
  LuMoon,
  LuSparkles,
  LuSun,
  LuX,
} from "react-icons/lu";

export const ICON_REGISTRY: Record<string, IconType> = {
  SiAngular,
  SiApachemaven,
  SiBootstrap,
  SiC,
  SiCplusplus,
  SiCss,
  SiDjango,
  SiDocker,
  SiDotnet,
  SiExpress,
  SiFastapi,
  SiFlask,
  SiGit,
  SiGithub,
  SiGithubactions,
  SiGraphql,
  SiHackerrank,
  SiHtml5,
  SiJavascript,
  SiJest,
  SiJquery,
  SiJupyter,
  SiKeras,
  SiKubernetes,
  SiLangchain,
  SiLeetcode,
  SiLinux,
  SiMongodb,
  SiMui,
  SiMysql,
  SiNestjs,
  SiNextdotjs,
  SiNgrx,
  SiNodedotjs,
  SiNumpy,
  SiPandas,
  SiPostgresql,
  SiPostman,
  SiPrisma,
  SiPython,
  SiPytorch,
  SiR,
  SiReact,
  SiReactivex,
  SiRedis,
  SiRedux,
  SiScikitlearn,
  SiSharp,
  SiSpring,
  SiSqlite,
  SiStrapi,
  SiStreamlit,
  SiTailwindcss,
  SiTensorflow,
  SiTypescript,
  SiVite,
  SiVuedotjs,

  FaBehance,
  FaCodepen,
  FaDev,
  FaDribbble,
  FaEnvelope,
  FaFacebook,
  FaGlobe,
  FaInstagram,
  FaJava,
  FaLinkedinIn,
  FaMedium,
  FaStackOverflow,
  FaXTwitter,
  FaYoutube,

  LuArrowLeft,
  LuArrowRight,
  LuArrowUp,
  LuArrowUpRight,
  LuCheck,
  LuChevronRight,
  LuCopy,
  LuDownload,
  LuExternalLink,
  LuFileText,
  LuLoaderCircle,
  LuMail,
  LuMenu,
  LuMoon,
  LuSparkles,
  LuSun,
  LuX,
};

export const PLATFORM_ICON: Record<string, IconType> = {
  github: SiGithub,
  linkedin: FaLinkedinIn,
  twitter: FaXTwitter,
  instagram: FaInstagram,
  facebook: FaFacebook,
  youtube: FaYoutube,
  medium: FaMedium,
  devto: FaDev,
  stackoverflow: FaStackOverflow,
  leetcode: SiLeetcode,
  hackerrank: SiHackerrank,
  codepen: FaCodepen,
  behance: FaBehance,
  dribbble: FaDribbble,
  email: FaEnvelope,
  website: FaGlobe,
};
