name: Portfolio CMS Docker Image
run-name: Build and Push Image to AWS ECR - ${{github.run_number}}
on:
  workflow_dispatch:
    inputs:
      version:
        description: Version of the Portfolio CMS to deploy
        required: true
        type: string
  push:
    tags: "*"
concurrency:
  group: portfolio-cms
  cancel-in-progress: true
jobs:
  build-date:
    name: Generate Build Date for Image
    runs-on: ubuntu-latest
    outputs:
      image-build-date: ${{steps.build-date.outputs.BUILD_DATE}}
    steps:
      - name: Generate build date
        id: build-date
        run: |
          BUILD_DATE=$(date -u +"%Y-%m-%d")
          echo "BUILD_DATE=$BUILD_DATE"
          echo "BUILD_DATE=$BUILD_DATE" >> "$GITHUB_OUTPUT"
  build-image:
    name: Build and Push Image to AWS ECR
    needs: [build-date]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Login to AWS
        id: login-aws
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: ap-south-1
          aws-access-key-id: ${{secrets.AWS_KEY}}
          aws-secret-access-key: ${{secrets.AWS_KEY_SECRET}}

      - name: Login in to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: true
          registry-type: private

      - name: Build and Push the Image to ECR
        id: build-push-image
        uses: docker/build-push-action@v7
        with:
          push: true
          tags: |
            ${{secrets.ECR_REGISTRY}}/portfolio/strapi-cms:${{inputs.version || github.ref_name}}
            ${{secrets.ECR_REGISTRY}}/portfolio/strapi-cms:latest
          context: ./cms
          build-args: |
            BUILD_DATE=${{needs.build-date.outputs.image-build-date}}
            VERSION=${{inputs.version || github.ref_name}}
            GIT_SHA=${{github.sha}}

      - name: Success Build
        id: success
        run: |
          echo "## Success :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "Build and Pushed Strapi CMS Docker Image to ECR : ${{inputs.version || github.ref_name}} " >> $GITHUB_STEP_SUMMARY
